# Generated by Django 5.1.7 on 2025-10-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_embeddings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
