# Generated by Django 5.1.7 on 2025-04-15 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='employee_id',
        ),
    ]
